//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public System.DateTime admin_DOB { get; set; }
        public string admin_address { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
