//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class token
    {
        public int token_id { get; set; }
        public string token_key { get; set; }
        public System.DateTime create_date { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
