//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tripe
    {
        public int tripe_id { get; set; }
        public string end_location { get; set; }
        public string start_location { get; set; }
        public string vechile_type { get; set; }
        public int price { get; set; }
        public Nullable<int> labour_number { get; set; }
        public System.DateTime dateandtime { get; set; }
        public string product_discription { get; set; }
        public string status { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> driver_id { get; set; }
        public string labour_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual driver driver { get; set; }
    }
}
